/**
 * Credentials Vault — AES-256 Encrypted Storage
 *
 * Handles secure storage/retrieval of:
 * - WhatsApp Business credentials
 * - API keys (OpenAI, Groq, etc.)
 * - Website URLs and auth tokens
 *
 * All sensitive data encrypted at rest using ENCRYPTION_KEY
 */

import crypto from 'crypto'

// ─── Types ───────────────────────────────────────────────────────────────────

export interface AgentCredentials {
  id: string
  user_id: string
  agent_id: string
  whatsapp_number?: string          // +91...
  whatsapp_verified?: boolean
  website_url?: string              // https://...
  website_verified?: boolean
  openai_api_key?: string           // encrypted
  groq_api_key?: string             // encrypted
  custom_ai_key?: string            // encrypted
  custom_ai_provider?: 'openai' | 'groq' | 'gemini' | 'anthropic'
  auth_token?: string               // encrypted (for webhook verification)
  webhook_url?: string              // generated by system
  created_at: Date
  last_verified: Date
  last_rotated: Date
}

export interface CredentialValidation {
  field: string
  valid: boolean
  message?: string
  suggestedFix?: string
}

// ─── Encryption Helpers ───────────────────────────────────────────────────────

const ENCRYPTION_KEY = process.env.ENCRYPTION_KEY || ''
const ALGORITHM = 'aes-256-gcm'

if (!ENCRYPTION_KEY || ENCRYPTION_KEY.length < 32) {
  throw new Error('ENCRYPTION_KEY must be set and at least 32 characters (256 bits)')
}

/**
 * Encrypt sensitive data using AES-256-GCM
 * Returns: iv.encryptedData.authTag (all base64)
 */
export function encryptCredential(plaintext: string): string {
  if (!plaintext) return ''

  const iv = crypto.randomBytes(12) // 96-bit IV for GCM
  const cipher = crypto.createCipheriv(ALGORITHM, Buffer.from(ENCRYPTION_KEY, 'hex'), iv)

  let encrypted = cipher.update(plaintext, 'utf8', 'hex')
  encrypted += cipher.final('hex')

  const authTag = cipher.getAuthTag()

  // Format: iv.encrypted.authTag (all base64)
  return [
    iv.toString('base64'),
    encrypted,
    authTag.toString('base64'),
  ].join('.')
}

/**
 * Decrypt sensitive data
 * Input format: iv.encryptedData.authTag
 */
export function decryptCredential(encrypted: string): string {
  if (!encrypted) return ''

  try {
    const [ivStr, encryptedStr, authTagStr] = encrypted.split('.')
    const iv = Buffer.from(ivStr, 'base64')
    const authTag = Buffer.from(authTagStr, 'base64')

    const decipher = crypto.createDecipheriv(ALGORITHM, Buffer.from(ENCRYPTION_KEY, 'hex'), iv)
    decipher.setAuthTag(authTag)

    let decrypted = decipher.update(encryptedStr, 'hex', 'utf8')
    decrypted += decipher.final('utf8')

    return decrypted
  } catch (err) {
    console.error('Decryption failed:', err)
    return ''
  }
}

// ─── Credential Validators ────────────────────────────────────────────────────

/**
 * Validate WhatsApp Business number
 * Format: +91XXXXXXXXXX (India)
 */
export function validateWhatsAppNumber(number: string): CredentialValidation {
  const cleaned = number.replace(/\D/g, '')

  if (!cleaned) {
    return {
      field: 'whatsapp_number',
      valid: false,
      message: 'WhatsApp number cannot be empty',
      suggestedFix: 'Enter your business WhatsApp number (with country code)',
    }
  }

  if (cleaned.length < 10) {
    return {
      field: 'whatsapp_number',
      valid: false,
      message: 'WhatsApp number too short',
      suggestedFix: 'Include country code (e.g., 919876543210)',
    }
  }

  if (cleaned.length > 15) {
    return {
      field: 'whatsapp_number',
      valid: false,
      message: 'WhatsApp number too long',
      suggestedFix: 'Remove any extra characters',
    }
  }

  // Format as +CC...
  const withPlus = '+' + cleaned
  return {
    field: 'whatsapp_number',
    valid: true,
    message: `Formatted as ${withPlus}`,
  }
}

/**
 * Validate website URL
 * Checks: Valid URL, accessible, not localhost
 */
export async function validateWebsiteUrl(url: string): Promise<CredentialValidation> {
  if (!url || !url.trim()) {
    return {
      field: 'website_url',
      valid: false,
      message: 'Website URL cannot be empty',
      suggestedFix: 'Enter your full website URL (e.g., https://www.example.com)',
    }
  }

  try {
    const urlObj = new URL(url)

    if (!['http:', 'https:'].includes(urlObj.protocol)) {
      return {
        field: 'website_url',
        valid: false,
        message: 'Only HTTP/HTTPS URLs allowed',
        suggestedFix: 'Use https://www.example.com format',
      }
    }

    if (urlObj.hostname === 'localhost' || urlObj.hostname === '127.0.0.1') {
      return {
        field: 'website_url',
        valid: false,
        message: 'Localhost/private IPs not allowed',
        suggestedFix: 'Use a public website URL',
      }
    }

    // Test accessibility (HEAD request, 5 second timeout)
    const controller = new AbortController()
    const timeoutId = setTimeout(() => controller.abort(), 5000)

    try {
      const res = await fetch(url, {
        method: 'HEAD',
        signal: controller.signal,
      })

      clearTimeout(timeoutId)

      if (res.status >= 200 && res.status < 400) {
        return {
          field: 'website_url',
          valid: true,
          message: `Website accessible (HTTP ${res.status})`,
        }
      } else {
        return {
          field: 'website_url',
          valid: false,
          message: `Website returned HTTP ${res.status}`,
          suggestedFix: 'Check if your website is online and accessible',
        }
      }
    } catch (err) {
      clearTimeout(timeoutId)
      return {
        field: 'website_url',
        valid: false,
        message: 'Website not accessible',
        suggestedFix: 'Verify the URL is correct and the site is online',
      }
    }
  } catch (err) {
    return {
      field: 'website_url',
      valid: false,
      message: 'Invalid URL format',
      suggestedFix: 'Use https://www.example.com format',
    }
  }
}

/**
 * Validate OpenAI API key format
 * Format: sk-... (at least 20 chars)
 */
export function validateOpenAIKey(key: string): CredentialValidation {
  if (!key || !key.trim()) {
    return {
      field: 'openai_api_key',
      valid: false,
      message: 'API key cannot be empty',
      suggestedFix: 'Paste your OpenAI API key from platform.openai.com',
    }
  }

  if (!key.startsWith('sk-')) {
    return {
      field: 'openai_api_key',
      valid: false,
      message: 'Invalid OpenAI key format (must start with sk-)',
      suggestedFix: 'Get a valid key from https://platform.openai.com/api-keys',
    }
  }

  if (key.length < 20) {
    return {
      field: 'openai_api_key',
      valid: false,
      message: 'API key too short',
      suggestedFix: 'Verify you copied the entire key correctly',
    }
  }

  return {
    field: 'openai_api_key',
    valid: true,
    message: 'Valid OpenAI key format',
  }
}

/**
 * Validate Groq API key format
 * Format: gsk_... (at least 20 chars)
 */
export function validateGroqKey(key: string): CredentialValidation {
  if (!key || !key.trim()) {
    return {
      field: 'groq_api_key',
      valid: false,
      message: 'API key cannot be empty',
      suggestedFix: 'Paste your Groq API key from console.groq.com',
    }
  }

  if (!key.startsWith('gsk_')) {
    return {
      field: 'groq_api_key',
      valid: false,
      message: 'Invalid Groq key format (must start with gsk_)',
      suggestedFix: 'Get a valid key from https://console.groq.com',
    }
  }

  if (key.length < 20) {
    return {
      field: 'groq_api_key',
      valid: false,
      message: 'API key too short',
      suggestedFix: 'Verify you copied the entire key correctly',
    }
  }

  return {
    field: 'groq_api_key',
    valid: true,
    message: 'Valid Groq key format',
  }
}

/**
 * Validate all credentials for a deployment
 */
export async function validateAllCredentials(creds: Partial<AgentCredentials>): Promise<CredentialValidation[]> {
  const results: CredentialValidation[] = []

  if (creds.whatsapp_number) {
    results.push(validateWhatsAppNumber(creds.whatsapp_number))
  }

  if (creds.website_url) {
    results.push(await validateWebsiteUrl(creds.website_url))
  }

  if (creds.openai_api_key) {
    results.push(validateOpenAIKey(creds.openai_api_key))
  }

  if (creds.groq_api_key) {
    results.push(validateGroqKey(creds.groq_api_key))
  }

  return results
}

// ─── Secure Credential Storage ────────────────────────────────────────────────

/**
 * Safe version of credentials (for API responses)
 * Hides all sensitive values
 */
export function sanitizeCredentials(creds: AgentCredentials): Record<string, unknown> {
  return {
    id: creds.id,
    agent_id: creds.agent_id,
    whatsapp_number: creds.whatsapp_number ? '●●●●●●●●●' : null,
    whatsapp_verified: creds.whatsapp_verified,
    website_url: creds.website_url,
    website_verified: creds.website_verified,
    openai_api_key: creds.openai_api_key ? '●●●●●●●●●●●●●●●●●●' : null,
    groq_api_key: creds.groq_api_key ? '●●●●●●●●●●●●●●●●●●' : null,
    custom_ai_provider: creds.custom_ai_provider,
    webhook_url: creds.webhook_url,
    last_verified: creds.last_verified,
    created_at: creds.created_at,
  }
}

/**
 * Generate secure webhook token (for webhook verification)
 */
export function generateWebhookToken(): string {
  return crypto.randomBytes(32).toString('hex')
}

/**
 * Verify webhook signature (HMAC-SHA256)
 */
export function verifyWebhookSignature(payload: string, signature: string, token: string): boolean {
  const computed = crypto.createHmac('sha256', token).update(payload).digest('hex')
  return crypto.timingSafeEqual(Buffer.from(computed), Buffer.from(signature))
}
