/**
 * Agent Template Definitions
 *
 * Defines which credentials and configuration each agent template requires.
 * This ensures consistent credential collection across all agents in the store.
 */

export interface TemplateCredentialRequirement {
  field:
    | 'whatsapp_number'
    | 'website_url'
    | 'openai_api_key'
    | 'groq_api_key'
    | 'use_diyaa_ai_powered'
  required: boolean
  description: string
}

export interface AgentTemplate {
  id: string
  agentType: string // maps to AgentType in all-prompts.ts
  name: string
  icon: string
  category: string
  description: string
  pain: string
  features: string[]
  targetBusiness: string
  badge?: string
  workflow?: boolean
  credentials: TemplateCredentialRequirement[]
}

// Credential requirement patterns
const PATTERN_WHATSAPP = {
  field: 'whatsapp_number' as const,
  required: true,
  description: 'WhatsApp Business Number for sending messages',
}

const PATTERN_WEBSITE = {
  field: 'website_url' as const,
  required: true,
  description: 'Your website URL for knowledge base context',
}

const PATTERN_WEBSITE_OPTIONAL = {
  field: 'website_url' as const,
  required: false,
  description: 'Your website URL (optional for knowledge base)',
}

const PATTERN_AI_MODEL = {
  field: 'use_diyaa_ai_powered' as const,
  required: true,
  description: 'AI Model selection (diyaa.ai powered or bring your own key)',
}

/**
 * Agent templates with their credential requirements
 * This is the source of truth for what each agent needs to function
 */
export const AGENT_TEMPLATES: AgentTemplate[] = [
  {
    id: 'task-master',
    agentType: 'teamexecutor',
    name: 'TaskMaster',
    icon: '📋',
    category: 'Operations',
    description:
      '5-agent workflow: Parse meetings → Assign tasks → Send notifications → Track progress → Report daily',
    pain: 'Monday meetings taking forever, tasks never get done',
    features: [
      'Parse meeting notes',
      'AI task extraction',
      'Smart assignment',
      'Multi-channel notifications',
      'Daily reports',
      'Progress tracking',
    ],
    targetBusiness: 'Any team with recurring meetings',
    badge: 'Multi-Agent 🚀',
    workflow: true,
    credentials: [PATTERN_WHATSAPP, PATTERN_AI_MODEL],
  },
  {
    id: 'lead-catcher',
    agentType: 'leadcatcher',
    name: 'LeadCatcher',
    icon: '🎯',
    category: 'Sales',
    description: 'WhatsApp lead capture + instant follow-up',
    pain: 'Never miss a lead again',
    features: ['Lead capture', 'Auto-follow-up', 'WhatsApp messages'],
    targetBusiness: 'Any business',
    credentials: [PATTERN_WHATSAPP, PATTERN_AI_MODEL],
  },
  {
    id: 'appoint-bot',
    agentType: 'appointbot',
    name: 'AppointBot',
    icon: '📅',
    category: 'Scheduling',
    description: 'Appointment booking + reminder via WhatsApp',
    pain: 'No-shows killing your business',
    features: ['Booking calendar', 'Reminders', 'Confirmations'],
    targetBusiness: 'Clinic, Salon, Gym, Consultant',
    credentials: [PATTERN_WHATSAPP, PATTERN_WEBSITE_OPTIONAL, PATTERN_AI_MODEL],
  },
  {
    id: 'pay-chaser',
    agentType: 'paymentreminder',
    name: 'PayChaser',
    icon: '💰',
    category: 'Collections',
    description: 'Payment due reminders + UPI link sender',
    pain: 'Chasing money manually',
    features: ['Due reminders', 'UPI links', 'Payment tracking'],
    targetBusiness: 'Any business with invoices',
    credentials: [PATTERN_WHATSAPP, PATTERN_AI_MODEL],
  },
  {
    id: 'gst-mate',
    agentType: 'invoicebot',
    name: 'GSTMate',
    icon: '📊',
    category: 'Accounting',
    description: 'GST invoice generation + GSTR reconciliation',
    pain: 'Complex GST compliance',
    features: ['Invoice generation', 'GSTR sync', 'Tax compliance'],
    targetBusiness: 'Every registered Indian business',
    credentials: [PATTERN_AI_MODEL],
  },
  {
    id: 'customer-support',
    agentType: 'customersupport',
    name: 'CustomerSupport',
    icon: '💬',
    category: 'Support',
    description: '24/7 WhatsApp/email/phone support',
    pain: 'Missing customer messages',
    features: ['Multi-channel', '24/7 support', 'Chat history'],
    targetBusiness: 'Retail, E-com, SaaS, D2C',
    credentials: [PATTERN_WHATSAPP, PATTERN_WEBSITE, PATTERN_AI_MODEL],
  },
  {
    id: 'review-guard',
    agentType: 'feedbackanalyzer',
    name: 'ReviewGuard',
    icon: '⭐',
    category: 'Reputation',
    description: 'Review monitoring + auto-response',
    pain: 'Bad reviews going unaddressed',
    features: ['Review monitor', 'Auto-reply', 'Multi-platform'],
    targetBusiness: 'Restaurant, Hotel, Salon, Retail',
    credentials: [PATTERN_WEBSITE, PATTERN_AI_MODEL],
  },
  {
    id: 'invoice-bot',
    agentType: 'invoicebot',
    name: 'InvoiceBot',
    icon: '📄',
    category: 'Accounting',
    description: 'Auto invoice + GST + UPI reconciliation',
    pain: 'Manual invoicing is time-consuming',
    features: ['Auto-invoice', 'GST handling', 'UPI integration'],
    targetBusiness: 'CA firms, Freelancers, MSMEs',
    credentials: [PATTERN_AI_MODEL],
  },
  // ── NEW TOP-20 AGENTS ─────────────────────────────────────────────────────
  {
    id: 'lead-intent',
    agentType: 'leadintent',
    name: 'LeadIntent',
    icon: '📊',
    category: 'Sales',
    description: 'AI scores every lead by buying intent in real-time',
    pain: 'Wasting time on cold leads while hot ones go cold',
    features: ['BANT scoring', 'Intent signals', 'Priority ranking', 'Smart routing'],
    targetBusiness: 'Sales teams, D2C, B2B',
    badge: 'AI Scoring 🧠',
    credentials: [PATTERN_AI_MODEL],
  },
  {
    id: 'sales-closer',
    agentType: 'salescloser',
    name: 'SalesCloser',
    icon: '🤝',
    category: 'Sales',
    description: 'Handles objections and pushes every conversation toward conversion',
    pain: 'Leads drop off before buying because no one follows up properly',
    features: ['Objection handling', 'Urgency creation', 'Deal stage tracking', 'Closing scripts'],
    targetBusiness: 'Consulting, SaaS, Real Estate, D2C',
    badge: 'Closes Deals 💰',
    credentials: [PATTERN_WHATSAPP, PATTERN_AI_MODEL],
  },
  {
    id: 'conversation-intel',
    agentType: 'conversationintel',
    name: 'ConversationIntel',
    icon: '🧠',
    category: 'Intelligence',
    description: 'Understands intent, emotion, and urgency in every message',
    pain: 'Not knowing what customers really want from their messages',
    features: ['Intent detection', 'Emotion analysis', 'Urgency scoring', 'Opportunity flags'],
    targetBusiness: 'Any business',
    badge: 'Deep Understanding 🔍',
    credentials: [PATTERN_AI_MODEL],
  },
  {
    id: 'churn-prevention',
    agentType: 'churnprevention',
    name: 'ChurnPrevention',
    icon: '🛡️',
    category: 'Retention',
    description: 'Detects at-risk customers early and wins them back automatically',
    pain: 'Customers leaving silently with no warning',
    features: ['Churn signals', 'Re-engagement flows', 'Retention offers', 'Win-back scripts'],
    targetBusiness: 'SaaS, Gyms, Subscriptions, D2C',
    credentials: [PATTERN_WHATSAPP, PATTERN_AI_MODEL],
  },
  {
    id: 'revenue-forecaster',
    agentType: 'revenueforecaster',
    name: 'RevenueForecaster',
    icon: '📈',
    category: 'Intelligence',
    description: 'Predicts your revenue and cash flow 90 days out',
    pain: "No visibility into next month's revenue",
    features: ['Revenue projection', 'Cash flow forecast', 'Churn impact', 'Growth rate'],
    targetBusiness: 'Any growing business',
    credentials: [PATTERN_AI_MODEL],
  },
  {
    id: 'lifetime-value',
    agentType: 'lifetimevalue',
    name: 'LifetimeValue',
    icon: '💎',
    category: 'Intelligence',
    description: 'Identifies your highest-value customers and how to keep them',
    pain: 'Treating all customers the same, losing your best ones',
    features: ['CLV calculation', 'Segment scoring', 'VIP detection', 'Upsell recommendations'],
    targetBusiness: 'E-commerce, Services, SaaS',
    credentials: [PATTERN_AI_MODEL],
  },
  {
    id: 'email-automator',
    agentType: 'emailautomator',
    name: 'EmailAutomator',
    icon: '✉️',
    category: 'Marketing',
    description: 'Automated email sequences for every stage of the customer journey',
    pain: 'Writing and sending emails manually for every customer',
    features: ['Welcome flows', 'Onboarding drips', 'Re-engagement', 'A/B testing'],
    targetBusiness: 'SaaS, E-commerce, Consulting',
    credentials: [PATTERN_AI_MODEL],
  },
  {
    id: 'decision-copilot',
    agentType: 'decisioncopilot',
    name: 'DecisionCopilot',
    icon: '🧭',
    category: 'Intelligence',
    description: 'Daily morning brief with your 3 most important business actions',
    pain: 'Starting every day without knowing what to focus on',
    features: ['Morning brief', 'Priority actions', 'Business health score', 'Daily digest'],
    targetBusiness: 'Business owners, Managers',
    badge: 'Daily Clarity 🌅',
    credentials: [PATTERN_AI_MODEL],
  },
  {
    id: 'process-automator',
    agentType: 'processautomator',
    name: 'ProcessAutomator',
    icon: '⚙️',
    category: 'Operations',
    description: 'Turn natural language into workflows automatically',
    pain: 'Manual repetitive processes eating up team time',
    features: ['Natural language input', 'Workflow builder', 'Trigger detection', 'Error handling'],
    targetBusiness: 'Operations, Admin, Finance teams',
    credentials: [PATTERN_AI_MODEL],
  },
  {
    id: 'business-insights',
    agentType: 'businessinsights',
    name: 'BusinessInsights',
    icon: '💡',
    category: 'Intelligence',
    description: "Explains what's happening in your business in plain language",
    pain: 'Staring at dashboards without understanding what they mean',
    features: [
      'Plain English insights',
      'Root cause analysis',
      'Trend explanation',
      'Action recommendations',
    ],
    targetBusiness: 'Any data-driven business',
    credentials: [PATTERN_AI_MODEL],
  },
  {
    id: 'market-intel',
    agentType: 'marketintel',
    name: 'MarketIntel',
    icon: '🔍',
    category: 'Intelligence',
    description: 'Tracks competitors and surfaces market opportunities automatically',
    pain: 'Missing competitor moves and market changes',
    features: [
      'Competitor tracking',
      'Trend alerts',
      'Pricing intelligence',
      'Strategic recommendations',
    ],
    targetBusiness: 'Any competitive market',
    credentials: [PATTERN_WEBSITE, PATTERN_AI_MODEL],
  },
  {
    id: 'document-processor',
    agentType: 'documentprocessor',
    name: 'DocumentProcessor',
    icon: '📄',
    category: 'Operations',
    description: 'Extract, analyze, and act on data from contracts, invoices, and forms',
    pain: 'Manually reading and entering data from documents',
    features: ['Contract analysis', 'Invoice extraction', 'Form filling', 'Compliance check'],
    targetBusiness: 'Legal, Finance, HR',
    credentials: [PATTERN_AI_MODEL],
  },
  {
    id: 'content-engine',
    agentType: 'contentengine',
    name: 'ContentEngine',
    icon: '✍️',
    category: 'Marketing',
    description: 'One idea → LinkedIn, Twitter, Instagram, WhatsApp content instantly',
    pain: 'Spending hours creating content for every platform separately',
    features: [
      'Multi-platform',
      'LinkedIn posts',
      'Twitter threads',
      'Video scripts',
      'WhatsApp broadcasts',
    ],
    targetBusiness: 'Creators, Brands, Agencies',
    badge: 'Go Viral ✨',
    credentials: [PATTERN_AI_MODEL],
  },
  {
    id: 'whats-blast',
    agentType: 'customersupport',
    name: 'WhatsBlast',
    icon: '📢',
    category: 'Marketing',
    description: 'WhatsApp campaign broadcast + segmentation',
    pain: 'No way to reach customers at scale',
    features: ['Broadcasts', 'Segmentation', 'Analytics'],
    targetBusiness: 'Any consumer business',
    credentials: [PATTERN_WHATSAPP],
  },
  {
    id: 'doc-harvest',
    agentType: 'documentprocessor',
    name: 'DocHarvest',
    icon: '📋',
    category: 'Operations',
    description: 'Client document collection automation',
    pain: 'Chasing clients for documents',
    features: ['Doc collection', 'Reminders', 'Organization'],
    targetBusiness: 'CA firm, Legal, Immigration',
    credentials: [PATTERN_WHATSAPP, PATTERN_AI_MODEL],
  },
  {
    id: 'nurture-bot',
    agentType: 'emailautomator',
    name: 'NurtureBot',
    icon: '🌱',
    category: 'Sales',
    description: 'Lead nurture drip sequence (multi-channel)',
    pain: 'Leads going cold without follow-up',
    features: ['Drip campaigns', 'Personalization', 'Multi-channel'],
    targetBusiness: 'Sales teams, D2C brands',
    credentials: [PATTERN_WHATSAPP, PATTERN_AI_MODEL],
  },
  {
    id: 'stock-sentinel',
    agentType: 'processautomator',
    name: 'StockSentinel',
    icon: '📦',
    category: 'Operations',
    description: 'Inventory reorder alert + supplier order',
    pain: 'Stockouts losing revenue',
    features: ['Stock alerts', 'Auto-reorder', 'Supplier sync'],
    targetBusiness: 'Pharmacy, Retail, FMCG',
    credentials: [PATTERN_WHATSAPP, PATTERN_AI_MODEL],
  },
  {
    id: 'patient-pulse',
    agentType: 'appointbot',
    name: 'PatientPulse',
    icon: '🏥',
    category: 'Healthcare',
    description: 'Patient follow-up + prescription refill reminder',
    pain: 'Patients forgetting follow-ups',
    features: ['Patient follow-up', 'Prescription reminder', 'Compliance'],
    targetBusiness: 'Clinic, Hospital, Diagnostic center',
    credentials: [PATTERN_WHATSAPP, PATTERN_AI_MODEL],
  },
  {
    id: 'resume-filter',
    agentType: 'documentprocessor',
    name: 'ResumeFilter',
    icon: '👤',
    category: 'HR',
    description: 'AI resume screening + shortlisting agent',
    pain: 'Manual resume screening is tedious',
    features: ['Resume screening', 'Shortlisting', 'Ranking'],
    targetBusiness: 'HR/Recruitment agency, IT firm',
    credentials: [PATTERN_AI_MODEL],
  },
  {
    id: 'social-sched',
    agentType: 'contentengine',
    name: 'SocialSched',
    icon: '📱',
    category: 'Marketing',
    description: 'Social media calendar + publisher (all platforms)',
    pain: 'Posting manually to every platform',
    features: ['Calendar', 'Multi-platform', 'Scheduling'],
    targetBusiness: 'Agency, D2C brand, Creator',
    credentials: [PATTERN_AI_MODEL],
  },
  {
    id: 'fee-collect',
    agentType: 'paymentreminder',
    name: 'FeeCollect',
    icon: '🎓',
    category: 'Education',
    description: 'Fee reminder + installment tracking agent',
    pain: 'Fee collection delays',
    features: ['Fee reminder', 'Installment tracking', 'Reporting'],
    targetBusiness: 'School, Coaching institute, Tuition',
    credentials: [PATTERN_WHATSAPP, PATTERN_AI_MODEL],
  },
  {
    id: 'foodie-care',
    agentType: 'customersupport',
    name: 'FoodieCare',
    icon: '🍔',
    category: 'Food & Beverage',
    description: 'Order tracking + feedback collection for restaurants',
    pain: 'Missing customer feedback and order issues',
    features: ['Order tracking', 'Feedback collection', 'Issue resolution'],
    targetBusiness: 'Restaurant, Cloud kitchen, Food delivery',
    credentials: [PATTERN_WHATSAPP, PATTERN_AI_MODEL],
  },
  {
    id: 'hotel-concierge',
    agentType: 'customersupport',
    name: 'HotelConcierge',
    icon: '🏨',
    category: 'Hospitality',
    description: 'Guest services + booking agent for hotels',
    pain: 'Missed guest requests and bookings',
    features: ['Room booking', 'Guest requests', 'Service coordination'],
    targetBusiness: 'Hotel, Resort, Guest house',
    credentials: [PATTERN_WHATSAPP, PATTERN_AI_MODEL],
  },
  {
    id: 'rent-collect',
    agentType: 'paymentreminder',
    name: 'RentCollect',
    icon: '🏠',
    category: 'Real Estate',
    description: 'Rent reminder + maintenance request handler',
    pain: 'Late rent payments and maintenance tracking',
    features: ['Rent reminders', 'Maintenance tickets', 'Payment tracking'],
    targetBusiness: 'Landlords, Property managers',
    credentials: [PATTERN_WHATSAPP, PATTERN_AI_MODEL],
  },
  {
    id: 'insurance-claim',
    agentType: 'processautomator',
    name: 'InsuranceClaim',
    icon: '🛡️',
    category: 'Insurance',
    description: 'Claim status tracker + document collection',
    pain: 'Lost claims and document confusion',
    features: ['Claim tracking', 'Doc collection', 'Status updates'],
    targetBusiness: 'Insurance agents, Brokers',
    credentials: [PATTERN_WHATSAPP, PATTERN_AI_MODEL],
  },
  {
    id: 'loan-manager',
    agentType: 'loanmanager',
    name: 'LoanManager',
    icon: '🏦',
    category: 'Finance',
    description: 'Loan application tracker + document verification',
    pain: 'Slow loan processing and follow-ups',
    features: ['Application tracking', 'Doc verification', 'Status updates'],
    targetBusiness: 'NBFC, Bank, Loan agent',
    credentials: [PATTERN_WHATSAPP, PATTERN_AI_MODEL],
  },
  {
    id: 'event-bot',
    agentType: 'appointbot',
    name: 'EventBot',
    icon: '🎪',
    category: 'Events',
    description: 'Event registration + reminder agent',
    pain: 'Low attendance and missed events',
    features: ['Registration', 'Reminders', 'Feedback collection'],
    targetBusiness: 'Event organizers, Corporate, Institutions',
    credentials: [PATTERN_WHATSAPP, PATTERN_AI_MODEL],
  },
  {
    id: 'travel-coord',
    agentType: 'appointbot',
    name: 'TravelCoord',
    icon: '✈️',
    category: 'Travel',
    description: 'Travel booking + itinerary management',
    pain: 'Travel planning chaos',
    features: ['Booking', 'Itinerary', 'Reminder'],
    targetBusiness: 'Travel agency, Corporate travel',
    credentials: [PATTERN_WHATSAPP, PATTERN_AI_MODEL],
  },
  {
    id: 'legal-case',
    agentType: 'processautomator',
    name: 'LegalCase',
    icon: '⚖️',
    category: 'Legal',
    description: 'Case timeline tracker + client communication',
    pain: 'Missed deadlines and client updates',
    features: ['Timeline tracking', 'Client updates', 'Deadline alerts'],
    targetBusiness: 'Lawyers, Law firms',
    credentials: [PATTERN_WHATSAPP, PATTERN_AI_MODEL],
  },
  {
    id: 'vendor-portal',
    agentType: 'processautomator',
    name: 'VendorPortal',
    icon: '🤝',
    category: 'Procurement',
    description: 'Vendor onboarding + payment tracker',
    pain: 'Vendor management chaos',
    features: ['Vendor onboarding', 'Payment tracking', 'Communication'],
    targetBusiness: 'Companies with multiple vendors',
    credentials: [PATTERN_WHATSAPP, PATTERN_AI_MODEL],
  },
  {
    id: 'attendance-bot',
    agentType: 'processautomator',
    name: 'AttendanceBot',
    icon: '✅',
    category: 'HR',
    description: 'Employee attendance + leave management',
    pain: 'Manual attendance tracking',
    features: ['Attendance tracking', 'Leave requests', 'Reports'],
    targetBusiness: 'Office, Factory, School',
    credentials: [PATTERN_WHATSAPP, PATTERN_AI_MODEL],
  },
  {
    id: 'salary-pilot',
    agentType: 'processautomator',
    name: 'SalaryPilot',
    icon: '💸',
    category: 'Finance',
    description: 'Salary processing + compliance tracker',
    pain: 'Salary processing errors',
    features: ['Salary processing', 'Compliance', 'Reports'],
    targetBusiness: 'HR teams, Payroll managers',
    credentials: [PATTERN_AI_MODEL],
  },
  {
    id: 'tax-helper',
    agentType: 'invoicebot',
    name: 'TaxHelper',
    icon: '📋',
    category: 'Finance',
    description: 'Tax deadline reminder + filing assistant',
    pain: 'Missing tax deadlines',
    features: ['Deadline reminders', 'Filing assistance', 'Compliance'],
    targetBusiness: 'CA firms, Taxpayers',
    credentials: [PATTERN_WHATSAPP, PATTERN_AI_MODEL],
  },
  {
    id: 'complaint-resolver',
    agentType: 'customersupport',
    name: 'ComplaintResolver',
    icon: '🎯',
    category: 'Support',
    description: 'Complaint acknowledgment + resolution tracker',
    pain: 'Unresolved complaints piling up',
    features: ['Acknowledgment', 'Escalation', 'Resolution tracking'],
    targetBusiness: 'Any customer-facing business',
    credentials: [PATTERN_WHATSAPP, PATTERN_AI_MODEL],
  },
  {
    id: 'warranty-tracker',
    agentType: 'processautomator',
    name: 'WarrantyTracker',
    icon: '🔧',
    category: 'Operations',
    description: 'Warranty claim + product registration',
    pain: 'Warranty claim confusion',
    features: ['Registration', 'Claim tracking', 'Expiry alerts'],
    targetBusiness: 'Electronics, Appliances, Retail',
    credentials: [PATTERN_WHATSAPP, PATTERN_AI_MODEL],
  },
  {
    id: 'membership-bot',
    agentType: 'paymentreminder',
    name: 'MembershipBot',
    icon: '💳',
    category: 'Membership',
    description: 'Membership renewal + benefits communicator',
    pain: 'Members forgetting to renew',
    features: ['Renewal reminders', 'Benefits info', 'Upsells'],
    targetBusiness: 'Gym, Club, Association',
    credentials: [PATTERN_WHATSAPP, PATTERN_AI_MODEL],
  },
  {
    id: 'product-launch',
    agentType: 'contentengine',
    name: 'ProductLaunch',
    icon: '🚀',
    category: 'Marketing',
    description: 'Product launch campaign coordinator',
    pain: 'Launch day chaos',
    features: ['Campaign planning', 'Content schedule', 'Analytics'],
    targetBusiness: 'E-commerce, D2C brands',
    credentials: [PATTERN_WHATSAPP, PATTERN_AI_MODEL],
  },
  {
    id: 'survey-scout',
    agentType: 'processautomator',
    name: 'SurveyScout',
    icon: '📝',
    category: 'Intelligence',
    description: 'Survey distribution + response analyzer',
    pain: 'Low survey response rates',
    features: ['Survey creation', 'Distribution', 'Analysis'],
    targetBusiness: 'Market researchers, HR',
    credentials: [PATTERN_AI_MODEL],
  },
  {
    id: 'partner-portal',
    agentType: 'processautomator',
    name: 'PartnerPortal',
    icon: '🔗',
    category: 'Partnerships',
    description: 'Partner onboarding + commission tracker',
    pain: 'Partner management complexity',
    features: ['Onboarding', 'Commission tracking', 'Communication'],
    targetBusiness: 'Channel partners, Franchise',
    credentials: [PATTERN_WHATSAPP, PATTERN_AI_MODEL],
  },
  {
    id: 'stock-alert',
    agentType: 'processautomator',
    name: 'StockAlert',
    icon: '📈',
    category: 'Finance',
    description: 'Stock price alerts + portfolio updates',
    pain: 'Missing important stock movements',
    features: ['Price alerts', 'Portfolio updates', 'News alerts'],
    targetBusiness: 'Investors, Traders',
    credentials: [PATTERN_AI_MODEL],
  },
  {
    id: 'audit-assist',
    agentType: 'processautomator',
    name: 'AuditAssist',
    icon: '🔍',
    category: 'Finance',
    description: 'Audit document collection + checklist tracker',
    pain: 'Audit preparation stress',
    features: ['Doc collection', 'Checklist', 'Deadline tracking'],
    targetBusiness: 'CA firms, Internal audit',
    credentials: [PATTERN_WHATSAPP, PATTERN_AI_MODEL],
  },
  // ── LANGRAPH MULTI-AGENT ENGINES ──────────────────────────────────────────
  {
    id: 'ai-cmo',
    agentType: 'ai-cmo',
    name: 'AI CMO',
    icon: '🧠',
    category: 'Marketing',
    description: 'Scrapes your website → understands your brand vibe → generates content that sounds exactly like you',
    pain: 'Content that sounds generic, not like your brand',
    features: [
      'Website scraping & brand analysis',
      'Tone & voice extraction',
      'Content pillar discovery',
      'LinkedIn posts in your voice',
      'Twitter/X threads',
      'Full marketing strategy',
    ],
    targetBusiness: 'Any business with a website',
    badge: 'Reads Your Brand 🎯',
    workflow: true,
    credentials: [PATTERN_WEBSITE, PATTERN_AI_MODEL],
  },
  {
    id: 'ai-sdr',
    agentType: 'ai-sdr',
    name: 'AI SDR',
    icon: '🤖',
    category: 'Sales',
    description: '6-agent SDR: Find leads → Outreach → Qualify → Schedule → Engage → Analyze',
    pain: 'No dedicated sales rep to find and qualify leads at scale',
    features: ['Lead discovery', 'Personalized outreach', 'BANT qualification', 'Meeting scheduling', 'Follow-up sequences', 'Pipeline analytics'],
    targetBusiness: 'B2B startups, SaaS, Consulting firms',
    badge: 'Multi-Agent 🚀',
    workflow: true,
    credentials: [PATTERN_WHATSAPP, PATTERN_AI_MODEL],
  },
  {
    id: 'ecommerce-ops',
    agentType: 'ecommerce',
    name: 'E-commerce Ops',
    icon: '🛒',
    category: 'Operations',
    description: 'Shopify order handler: New orders → Inventory → Shipping → Returns → Analytics',
    pain: 'Manual order processing and inventory management eating team time',
    features: ['Order automation', 'Inventory sync', 'Shipping updates', 'Return processing', 'Revenue analytics'],
    targetBusiness: 'Shopify stores, D2C brands, Online retailers',
    badge: 'Shopify Native 🛍️',
    workflow: true,
    credentials: [PATTERN_WHATSAPP, PATTERN_AI_MODEL],
  },
  {
    id: 'social-media-manager',
    agentType: 'social-media-manager',
    name: 'Social Media Manager',
    icon: '📲',
    category: 'Marketing',
    description: '4-agent social engine: Strategy → Content → Schedule → Analyze performance',
    pain: 'Spending hours creating and posting content across all platforms',
    features: ['Content strategy', 'Multi-platform posts', 'Hashtag optimization', 'Scheduling', 'Engagement tracking', 'Performance reports'],
    targetBusiness: 'Brands, Agencies, Creators, D2C',
    badge: 'Multi-Platform 🌐',
    workflow: true,
    credentials: [PATTERN_AI_MODEL],
  },
  {
    id: 'competitor-intel',
    agentType: 'competitor-intel',
    name: 'CompetitorIntel',
    icon: '🕵️',
    category: 'Intelligence',
    description: 'Tracks competitor pricing, features, and ads — alerts you every 6 hours',
    pain: 'Missing competitor moves and losing deals to unknown price changes',
    features: ['Pricing monitoring', 'Feature tracking', 'Ad intelligence', 'Alert system', 'Strategic recommendations'],
    targetBusiness: 'Any competitive market — SaaS, E-commerce, Services',
    badge: 'Real-time 📡',
    credentials: [PATTERN_WEBSITE, PATTERN_AI_MODEL],
  },
  {
    id: 'sales-intelligence',
    agentType: 'sales-intelligence',
    name: 'Sales Intelligence',
    icon: '🧠',
    category: 'Sales',
    description: 'Combines conversation intent analysis with 90-day revenue forecasting',
    pain: 'No visibility into which deals will close and what revenue is coming',
    features: ['Intent scoring', 'Revenue forecasting', 'Deal risk alerts', 'Win/loss analysis', 'Pipeline health'],
    targetBusiness: 'Sales teams, Founders, Revenue leaders',
    badge: 'AI Powered 💡',
    credentials: [PATTERN_AI_MODEL],
  },
  {
    id: 'content-marketing',
    agentType: 'content-marketing',
    name: 'Content Marketing',
    icon: '✍️',
    category: 'Marketing',
    description: 'Research → Write → Optimize → Distribute content across all channels',
    pain: 'Content creation is slow, inconsistent, and not SEO-optimized',
    features: ['Topic research', 'SEO writing', 'Multi-format (blog/social/email)', 'Distribution automation', 'Performance tracking'],
    targetBusiness: 'SaaS, Agencies, E-commerce, Consultants',
    badge: 'Full Funnel 🎯',
    workflow: true,
    credentials: [PATTERN_WEBSITE_OPTIONAL, PATTERN_AI_MODEL],
  },
]

/**
 * Get template by ID
 */
export function getTemplate(templateId: string): AgentTemplate | undefined {
  return AGENT_TEMPLATES.find((t) => t.id === templateId)
}

/**
 * Get credential requirements for a template
 */
export function getCredentialRequirements(templateId: string): TemplateCredentialRequirement[] {
  const template = getTemplate(templateId)
  return template?.credentials || []
}

/**
 * Check if a template requires a specific credential
 */
export function requiresCredential(
  templateId: string,
  field: TemplateCredentialRequirement['field']
): boolean {
  const reqs = getCredentialRequirements(templateId)
  const req = reqs.find((r) => r.field === field)
  return req?.required || false
}

/**
 * Get all required credential fields for a template
 */
export function getRequiredCredentials(
  templateId: string
): TemplateCredentialRequirement['field'][] {
  const reqs = getCredentialRequirements(templateId)
  return reqs.filter((r) => r.required).map((r) => r.field)
}
